- name: mkdir .ssh
  file: 
    path: ~/.ssh/
    state: directory
    owner: root
    group: root
    mode: 700
  handler: sshd_restart

- name: set authorized_keys
  vars_files:

  lineinfile:
    path: ~/.ssh/authorized_keys
    regexp: '^host='
  with_items:
    ;
  file:
    state: file
    owner: root
    group: root
    mode: 600
  handler: authorized_keys

- name: copy docker-compose.yaml to host
  copy:
    src: ../../../docker-compose/
    dest: ~/

- name: rename host in inputs.conf
  lineinfile:
    path: ~/docker-compose/inputs.conf
    regexp: '^host='
    line: '^host={{ ansible_hostname  }}'

