- name: download docker-compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: copy docker-compose.yaml to host
  become: yes
  become_user: "{{ remote_user }}"
  copy:
    src: ../../../docker-compose/
    dest: ~/docker-compose

- name: rename host in inputs.conf
  become: yes
  become_user: "{{ remote_user }}"
  lineinfile:
    path: ~/docker-compose/inputs.conf
    regexp: 'host.*=.*'
    line: 'host={{ inventory_hostname }}'

