- name: download docker-compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: copy docker-compose.yaml to host
  become: false
  copy:
    src: ../../../docker-compose/
    dest: ~/docker-compose

- name: rename host in inputs.conf
  become: false
  lineinfile:
    path: ~/docker-compose/inputs.conf
    regexp: '^host='
    line: '^host={{ ansible_hostname }}'

