version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  splunk-uf:
    image: splunk/universalforwarder
    hostname: example.com # set to fqdn of host
    ports:
      - 9997:9997
    environment:
      - "SPLUNK_START_ARGS=--accept-license"
      - "SPLUNK_PASSWORD=onkenwild"
    volumes:
      - /var/log:/var/log:ro
      - ./inputs.conf:/opt/splunkforwarder/etc/system/local/inputs.conf
      - ./outputs.conf:/opt/splunkforwarder/etc/system/local/outputs.conf
