- hosts: all
  become: true
  vars:
    remote_user: isucon
  roles:
    - common
    - docker-ce
  tasks:
    - name: copy compose.yaml to host
      copy:
        src: ./files/compose.yaml
        dest: "/home/{{ remote_user }}/"
